import type { DayPlan } from '../../../types'

const metroHints = {
  west: {
    marais: '地铁 1 号线方向 La Défense，在 Charles de Gaulle–Étoile 下车（约 20–25 分钟）。',
    opera: '地铁 1 号线至 Charles de Gaulle–Étoile（约 10–12 分钟）。',
    boulevards: '地铁 8/9 换 1 号线，或步行至 Opéra 再乘 1 号线（约 15–20 分钟）。',
    saintGermain: '地铁 4 换 1 号线，或 12 号线至 Franklin D. Roosevelt 再步行（约 20–25 分钟）。',
    latin: '地铁 4 换 1 号线至 Étoile（约 25 分钟）。',
    trocadero: '步行或地铁 1/2/6 号线短程至 Charles de Gaulle–Étoile（约 10–15 分钟）。',
    custom: '请从最近地铁站前往 Charles de Gaulle–Étoile（1 号线）。',
  },
  canal: {
    marais: '步行或地铁 8 号线短程至 République，再走向运河（约 15–20 分钟）。',
    opera: '地铁 7/8/9 至 République（约 10–15 分钟）。',
    boulevards: '地铁 8/9 至 République（约 8–12 分钟）。',
    saintGermain: '地铁 4 换 11 或 8 号线至 République（约 20–25 分钟）。',
    latin: '地铁 4 换 République 方向（约 20–25 分钟）。',
    trocadero: '地铁 9 号线直达 République（约 25–35 分钟）。',
    custom: '导航至 République 或 Goncourt 地铁站，再短步行到运河。',
  },
  left: {
    marais: '地铁 1 换 4 号线至 Saint-Germain / Odéon（约 15–20 分钟）。',
    opera: '地铁 3/7/8 换 4 号线（约 15–20 分钟）。',
    boulevards: '地铁 8/9 换 4 号线（约 15 分钟）。',
    saintGermain: '步行或地铁 1 站即可（约 5–10 分钟）。',
    latin: '步行或地铁短程（约 5–10 分钟）。',
    trocadero: '地铁 6 换 4 号线，或 10 号线至 Odéon / Mabillon（约 20–30 分钟）。',
    custom: '导航至 Odéon 或 Saint-Sulpice，再去卢森堡公园。',
  },
  disney: {
    marais: '地铁到 Châtelet / Nation 换乘 RER A（方向 Marne-la-Vallée），全程约 45–60 分钟。',
    opera: '地铁到 Auber 换乘 RER A（约 45–55 分钟）。',
    boulevards: '地铁到 Auber / Châtelet 换乘 RER A（约 45–55 分钟）。',
    saintGermain: '地铁到 Châtelet 换乘 RER A（约 50–60 分钟）。',
    latin: '地铁到 Châtelet 换乘 RER A（约 50–60 分钟）。',
    trocadero: '地铁 1/9 号线至 Châtelet 或 Auber 换乘 RER A（约 55–70 分钟）。',
    custom: '前往 RER A 沿线站点，终点 Marne-la-Vallée–Chessy。',
  },
  airport: {
    marais: 'RER B 自 Châtelet–Les Halles 或 Gare du Nord 前往 CDG（约 35–50 分钟 + 预留安检）。',
    opera: 'RER E/地铁至 Gare du Nord 换乘 RER B，或直接打车（约 45–70 分钟）。',
    boulevards: '地铁至 Gare du Nord 换乘 RER B（约 40–55 分钟）。',
    saintGermain: '地铁至 Châtelet 或 Saint-Michel 换乘 RER B（约 45–60 分钟）。',
    latin: 'RER B 可在 Saint-Michel–Notre-Dame 上车（约 35–50 分钟）。',
    trocadero: '地铁 1/9 至 Châtelet 换乘 RER B，或直接打车（约 50–75 分钟 + 预留安检）。',
    custom: '优先 RER B 或预留出租车到 CDG，出发前 3–3.5 小时离开酒店。',
  },
}

export const itinerary: DayPlan[] = [
  {
    day: 1,
    title: '抵达巴黎',
    theme: '落地 · 安顿 · 早睡',
    pace: '轻松',
    summary:
      'AF375 约上午抵达 CDG。只做酒店入住、一杯咖啡和轻松晚餐，倒时差优先。',
    metroHintFromArea: {
      marais: 'CDG → RER B 到 Châtelet / Saint-Michel，再转地铁到酒店（约 50–70 分钟）。也可出租车约 45–70 分钟。',
      opera: 'CDG → RER B 到 Gare du Nord，再地铁到酒店（约 45–60 分钟）。',
      boulevards: 'CDG → RER B 到 Gare du Nord / Châtelet，再短程地铁（约 50–65 分钟）。',
      saintGermain: 'CDG → RER B 到 Saint-Michel，步行/地铁到酒店（约 50–65 分钟）。',
      latin: 'CDG → RER B 到 Saint-Michel–Notre-Dame（约 40–55 分钟）。',
      trocadero: 'CDG → RER B 到 Châtelet，再地铁 1/9 号线到 Trocadéro / Passy；或出租车直达 16 区（约 55–75 分钟）。',
      custom: 'CDG 推荐 RER B 或出租车到酒店；抵达后先办理入住。',
    },
    stops: [
      {
        // Filled at runtime from flight arrival + CDG exit buffer + airport→hotel transit.
        time: '待定',
        placeId: 'hotel-selected',
        note: '从 CDG 出关后先到酒店办理入住、放下行李，稍作休息再出门。',
        transport: 'RER B / 出租车自戴高乐机场',
        walkLevel: '很少走',
        duration: '入住 30–45 分钟',
      },
      {
        time: '12:00',
        placeId: 'cafe-boots',
        note: '在酒店附近咖啡馆提神（若酒店不在玛黑，可改去地图上距酒店最近的 4.4+ 咖啡馆）。',
        transport: '酒店附近短步行',
        walkLevel: '短步行',
        duration: '45 分钟',
      },
      {
        time: '18:30',
        placeId: 'rest-early',
        note: '轻松晚餐，21:30 前回到酒店。',
        transport: '地铁或步行 5–10 分钟圈内',
        walkLevel: '短步行',
        duration: '60 分钟',
      },
    ],
  },
  {
    day: 2,
    title: '西侧经典',
    theme: '凯旋门 · 香榭丽舍 · 蒙索公园',
    pace: '适中',
    summary: '想去的香街与凯旋门集中在一天，中段散步即可，下午公园休息。',
    metroHintFromArea: metroHints.west,
    stops: [
      {
        time: '09:30',
        placeId: 'cafe-kitsune',
        note: '从咖啡馆开始；再地铁去凯旋门，避免清晨空腹登顶。',
        transport: '地铁至 Palais Royal 一带',
        walkLevel: '短步行',
        duration: '45 分钟',
      },
      {
        time: '11:00',
        placeId: 'attr-arc',
        note: '可购票登顶；电梯+台阶，量力而行。',
        transport: '地铁 1 号线至 Charles de Gaulle–Étoile',
        walkLevel: '短步行',
        duration: '75 分钟',
      },
      {
        time: '12:45',
        placeId: 'attr-champs',
        note: '只走中段橱窗与街景，不走完全程。',
        transport: '从凯旋门向东步行约 10–15 分钟',
        walkLevel: '短步行',
        duration: '45 分钟',
      },
      {
        time: '13:45',
        placeId: 'rest-clown',
        note: '午餐。若排队长，可在 Google Maps 换附近评分更高的空位店。',
        transport: '地铁 1/2/6 或短程到七区',
        walkLevel: '短步行',
        duration: '75 分钟',
      },
      {
        time: '16:00',
        placeId: 'attr-monceau',
        note: '公园休息，秋天很舒服。',
        transport: '地铁 2 号线至 Monceau',
        walkLevel: '很少走',
        duration: '60 分钟',
      },
      {
        time: '19:30',
        placeId: 'rest-asuka',
        note: '换日料口味；请用 Google Maps 确认当日营业。',
        transport: '地铁回右岸中心',
        walkLevel: '短步行',
        duration: '70 分钟',
      },
    ],
  },
  {
    day: 3,
    title: '右岸生活感',
    theme: '运河 · 廊街 · 玛黑',
    pace: '适中',
    summary: '不进大馆，沿着运河与玛黑慢慢逛，步行控制在短段。',
    metroHintFromArea: metroHints.canal,
    stops: [
      {
        time: '09:30',
        placeId: 'cafe-haute',
        note: '运河旁咖啡开场。',
        walkLevel: '短步行',
        duration: '45 分钟',
      },
      {
        time: '10:30',
        placeId: 'attr-canal',
        note: '沿河走一小段铁桥与树荫即可。',
        walkLevel: '短步行',
        duration: '50 分钟',
      },
      {
        time: '12:00',
        placeId: 'rest-laza',
        note: '中东菜午餐，适合分享。',
        transport: '短程步行或 1 站地铁',
        walkLevel: '短步行',
        duration: '75 分钟',
      },
      {
        time: '14:30',
        placeId: 'attr-passages',
        note: '有盖廊街避雨、少走路。',
        transport: '地铁至 Grands Boulevards',
        walkLevel: '很少走',
        duration: '45 分钟',
      },
      {
        time: '16:00',
        placeId: 'attr-marais-walk',
        note: '孚日广场坐下休息。',
        transport: '地铁 8 号线至 Chemin Vert / Bastille',
        walkLevel: '短步行',
        duration: '60 分钟',
      },
      {
        time: '19:30',
        placeId: 'rest-breizh',
        note: '布列塔尼薄饼晚餐。',
        walkLevel: '短步行',
        duration: '75 分钟',
      },
    ],
  },
  {
    day: 4,
    title: '左岸轻松',
    theme: '卢森堡 · 圣路易岛',
    pace: '轻松',
    summary: '公园与小岛，节奏放慢；地铁减少换乘。',
    metroHintFromArea: metroHints.left,
    stops: [
      {
        time: '09:45',
        placeId: 'cafe-odette',
        note: '圣日耳曼咖啡开场（可换成附近评分更高的精品店）。',
        walkLevel: '短步行',
        duration: '50 分钟',
      },
      {
        time: '11:00',
        placeId: 'attr-luxembourg',
        note: '找椅子坐着看书或发呆，比快走一圈更舒服。',
        walkLevel: '很少走',
        duration: '80 分钟',
      },
      {
        time: '13:00',
        placeId: 'rest-east',
        note: '意餐午餐，份量足。',
        transport: '地铁或短程',
        walkLevel: '短步行',
        duration: '75 分钟',
      },
      {
        time: '15:30',
        placeId: 'attr-ile',
        note: '圣路易岛短逛，不拉长步行。',
        transport: '地铁至 Pont Marie',
        walkLevel: '短步行',
        duration: '50 分钟',
      },
      {
        time: '19:30',
        placeId: 'rest-fish',
        note: '海鲜小食晚餐；订位或早到。',
        transport: '地铁短程',
        walkLevel: '短步行',
        duration: '80 分钟',
      },
    ],
  },
  {
    day: 5,
    title: '巴黎迪士尼',
    theme: 'RER A 乐园日',
    pace: '乐园日',
    summary: '公共交通往返，不租车。早出晚归，预留回程疲惫。',
    metroHintFromArea: metroHints.disney,
    stops: [
      {
        time: '07:45',
        placeId: 'cafe-disney-start',
        note: '出发前吃好喝好；也可买可携带的轻食。',
        walkLevel: '短步行',
        duration: '35 分钟',
      },
      {
        time: '09:30',
        placeId: 'attr-disney',
        note: '建议提前 App 排队与演出；中午在园内解决。',
        transport: 'RER A → Marne-la-Vallée–Chessy（约 45–60 分钟）',
        walkLevel: '中等步行',
        duration: '全天',
      },
      {
        time: '19:00',
        placeId: 'rest-disney',
        note: 'Disney Village 简餐或回城后就近吃。',
        transport: '傍晚 RER A 回城约 45–60 分钟',
        walkLevel: '短步行',
        duration: '60 分钟',
      },
    ],
  },
  {
    day: 6,
    title: '枫丹白露自驾',
    theme: '城堡 · 森林 · 小镇午餐',
    pace: '自驾日',
    summary: '市区边缘取车，往返约 1–1.5 小时/单程。注意低排放区与停车。',
    metroHintFromArea: {
      marais: '建议在 Bercy / Gare de Lyon 一带取车，减少进城驾驶。',
      opera: '可在圣拉扎尔或东北缘取还车点取车。',
      boulevards: '向东到合适租车点，避免穿行市中心。',
      saintGermain: '左岸取车点或东缘取车，导航避开小岛。',
      latin: '优先东缘/东南缘取车点。',
      trocadero: '西侧/环线边缘取车更顺，避开塞纳河小岛与右岸中心拥堵。',
      custom: '选择酒店附近或环线边缘的租车点，回城还车后再坐地铁。',
    },
    stops: [
      {
        time: '08:30',
        placeId: 'cafe-fontaine',
        note: '丰盛早午餐后再取车。',
        walkLevel: '短步行',
        duration: '60 分钟',
      },
      {
        time: '11:00',
        placeId: 'attr-fontainebleau',
        note: '城堡参观；可租讲解器。开车约 1–1.5 小时。',
        transport: '自驾 A6 方向',
        walkLevel: '短步行',
        duration: '3 小时',
      },
      {
        time: '14:15',
        placeId: 'rest-fontaine-town',
        note: '小镇午餐，出发前用 Google Maps 确认评分与空位。',
        walkLevel: '短步行',
        duration: '75 分钟',
      },
      {
        time: '16:00',
        placeId: 'attr-forest',
        note: '森林短停拍照，不要安排长距离徒步。',
        transport: '自驾 10–20 分钟',
        walkLevel: '短步行',
        duration: '45 分钟',
      },
      {
        time: '20:00',
        placeId: 'rest-return-eve',
        note: '还车回城后就近晚餐。',
        transport: '自驾回城约 1–1.5 小时 + 还车',
        walkLevel: '很少走',
        duration: '60 分钟',
      },
    ],
  },
  {
    day: 7,
    title: '返程',
    theme: '咖啡 · 出发去机场',
    pace: '轻松',
    summary: '只留一杯咖啡与出发缓冲。按返程航班时刻倒推离开酒店时间。',
    metroHintFromArea: metroHints.airport,
    stops: [
      {
        time: '08:30',
        placeId: 'cafe-depart',
        note: '浅坐即可，检查护照与登机牌。',
        walkLevel: '短步行',
        duration: '35 分钟',
      },
      {
        time: '按航班倒推',
        placeId: 'attr-cdg',
        note: '国际航班建议起飞前 3–3.5 小时到 CDG。按返程 AF374 时刻倒推离开酒店时间（一般需预留 3–3.5 小时）。',
        transport: 'RER B 或出租车',
        walkLevel: '很少走',
        duration: '离境',
      },
    ],
  },
]
